email_xpath = "//input[@placeholder='Email or Username']"
password_xpath = "//input[@placeholder='Password']"
login_xpath = "//button[contains(text(), 'Login')]"
warning_message1 = "/html/body/div/div/div/div/div[2]/div/div/div[1]"
close_warning_message1 = "//div//button[@class='close']"
warning_message2 = "//p[text() = '* This field may not be blank.']"
