# users section xpath
users = "//a[text()='Users']"
settings_tab = "//p[contains(text(),'Settings')]"
create_btn = "//div[@class='col-2']//button[text()='Create']"
first_name = "//div[@class='modal-content']//div[1]//input[@class='inline-form-control-count-with-box form-control is-invalid']"
last_name = "//div[@class='modal-content']//div[2]//input[@class='inline-form-control-count-with-box form-control is-invalid']"
e_mail = "//div[@class='row'][2]//input"
user_name = "//div[@class='row'][2]//input[@maxlength]"
user_type = "//div[@class='row'][3]//input"
create_user_submit = "//button[contains(text(),'Submit')]"
users_section_action_dropdown = "//div[contains(text(),'Actions')]"
action_dp_delete = "//ul[@x-placement='bottom-end']//li[text()='Delete']"
delete_confirmation_yes = "//button[contains(text(),'Yes')]"
delete_confirmation_no = "//button[contains(text(),'No')]"

# create team xpath's.
team_section = "//a[text()='Teams']"
create_user_btn = "//div[@class='col-1']//button[text()='Create']"
team_name = "//div[@style='padding: 7px;']/form/div[1]//div[@class='col-sm-10']/input"
team_desc = "//div[@style='padding: 7px;']/form/div[2]//div[@class='col-sm-10']/textarea"
create_team_submit = "//button[contains(text(), 'Submit')]"
search_field = "/html/body/div/div/div[2]/section/div/div[1]/div/div/div[2]/div/div/div[11]/div[2]/div[1]/div/div/div[2]/div[2]/div/div/div[1]/div[3]/input"
teams_section_action_dropdown = "//tr[@aria-rowindex='1']//td[@aria-colindex='4' and @data-label=' ']"
# users_section_action_dropdown = "//div[contains(text(),'Actions')]"
update = "//ul[@x-placement='top-end']//li[1]"
delete = "//ul[@x-placement='top-end']//li[2]"
add_users = "//ul[@x-placement='top-end']//li[3]"
select_users_dp = "//div[@class='dropdown v-select searchable']//input"
select_users_submit = "//button[contains(text(),'Submit')]"

# Domain xpath's
domain_section = "//a[text()='Domains']"
domain_create = "/html/body/div/div/div[2]/section/div/div[1]/div/div/div[2]/div/div/div[11]/div[2]/div[1]/div/div/div[2]/div[3]/div[1]/div/div/div[1]/button"
domain_name_field = "//input[@placeholder='Enter Domain']"
domain_name_submit = "/html/body/div/div/div[2]/section/div/div[1]/div/div/div[2]/div/div/div[11]/div[2]/div[1]/div/div/div[2]/div[3]/div[2]/div/div[1]/div/div/footer/div/button[2]"
domain_create_popup_close = "/html/body/div/div/div[2]/section/div/div[1]/div/div/div[2]/div/div/div[11]/div[2]/div[1]/div/div/div[2]/div[3]/div[2]/div/div[1]/div/div/header/button"
doamin_action_dropdown = "/html/body/div/div/div[2]/section/div/div[1]/div/div/div[2]/div/div/div[11]/div[2]/div[1]/div/div/div[2]/div[3]/div[1]/div/table/tbody/tr[1]/td[2]/div/div/span/div/div[1]"
domain_actiondp_delete = "//ul[@x-placement='bottom-end']//li[text()='Delete']"
domain_delete_confirm_popup = "/html/body/div/div/div[2]/section/div/div[2]/div/div[1]/div/div/footer/div/div/button[2]"
domain_actiondp_update = "//ul[@x-placement='top-end']//li[text()='Update']"
domain_search_field = "/html/body/div/div/div[2]/section/div/div[1]/div/div/div[2]/div/div/div[11]/div[2]/div[1]/div/div/div[2]/div[3]/div[1]/div/div/div[3]/input"


# vul_label_modification_and_notification
vul_label_modification_and_notification = "//a[text()='Vulnerability Label Modification and Notifications']"
severity_labels = "//a[text()='Severity Labels']"
high = "//div[@class='tab-content']//div[@class='row my-1'][1]//div[2]//input"
medium = "//div[@class='tab-content']//div[@class='row my-1'][2]//div[2]//input"
low = "//div[@class='tab-content']//div[@class='row my-1'][3]//div[2]//input"
info = "//div[@class='tab-content']//div[@class='row my-1'][4]//div[2]//input"
severity_labels_submit = "//button[contains(text(),'Submit')]"
warning_message = "//p[contains(text(),' * Ensure this field has no more than 10 characters.')]"

notification = "//a[text()='Notifications']"
application_notification = "//div[@class='list-group']//div[1]//label//div/div"
engagement_notification = "//div[@class='list-group']//div[2]//label//div/div"
scan_notification = "//div[@class='list-group']//div[3]//label//div/div"
users_notification = "//div[@class='list-group']//div[4]//label//div/div"
teams_notification = "//div[@class='list-group']//div[5]//label//div/div"

